[package]
name = "dsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "dsc"
path = "src\\main\\main.rs"
[[test]]
name = "main_test"
path = "src\\test\\main_test.rs"